---
title: "Week 03 Assignment"
author: "Max Wagner"
date: "September 12, 2015"
output: html_document
---

Loading the libraries needed and the data from the csv file.
```{r}
library(RCurl)
library(plyr)
dat <- data.frame(read.csv(text = getURL("https://raw.githubusercontent.com/maxwagner/607/master/week03/bridges.csv"), header = FALSE))
```

***
Pick some columns to look at, and give them names.
```{r}
colnames(dat) <- c("id", "river", "location", "erected", "purpose", "length", "lanes", "clear_g", "t_or_d", "material", "span", "rel_l", "type")
bridges <- subset(dat, select = c(1, 5, 9, 10))
head(bridges)
```

***
Rename and alter some values in the columns with plyr.
```{r}
bridges$id <- tolower(bridges$id)
bridges$t_or_d <- revalue(bridges$t_or_d, c("THROUGH" = "through", "DECK" = "deck"))
bridges$purpose <- revalue(bridges$purpose, c("WALK" = "walk", "AQUEDUCT" = "aqdt", "RR" = "rr", "HIGHWAY" = "hwy"))
bridges$material <- revalue(bridges$material, c("WOOD" = "wood", "IRON" = "iron", "STEEL" = "steel"))
head(bridges)
```

***
Subset some rows...
```{r}
bridges <- subset(bridges, material == "iron" | purpose == "aqdt")
head(bridges)
```